name: main
on:
  - push
  - pull_request

jobs:
  install:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 12.x

    steps:
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/checkout@v2

      - name: Installing
        run: yarn --frozen-lockfile

      # - name: Lint
      #   run: yarn lint
      # - name: Unit tests
      #   run: yarn test --coverage --coverageReporters=lcov --coverageReporters=text-summary
      # - name: Send test coverage to codecov
      #   continue-on-error: true
      #   uses: codecov/codecov-action@v1

  release:
    needs: [install]
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - uses: actions/checkout@v2

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
        env:
          GIT_AUTHOR_EMAIL: ${{ secrets.GIT_AUTHOR_EMAIL }}
          GIT_AUTHOR_NAME: ${{ secrets.GIT_AUTHOR_NAME }}
          GIT_COMMITTER_EMAIL: ${{ secrets.GIT_AUTHOR_EMAIL }}
          GIT_COMMITTER_NAME: ${{ secrets.GIT_AUTHOR_NAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
